name: mazdoorhub
description: MazdoorHub Flutter app (Beta MVP) — jobs, chat, payments, maps, offline.
publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.5.0+1
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  web_socket_channel: ^2.4.5
  url_launcher: ^6.3.0
  flutter_map: ^6.2.1
  latlong2: ^0.9.1
  flutter_tts: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
